trigger:
  - main
  - refs/tags/*

pr:
  - main
  
parameters:
- name: RunExtendedTests
  displayName: Run Extended Tests?
  type: boolean
  default: false
  
variables:
  # Variables used by both AndroidX/GPS go in the template
  - template: build/ci/variables.yml@self
  
  # Variables only used by AndroidX go here
  - name: skipUnitTests
    value: false

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:   
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
      
    stages:
    - stage: build_windows
      displayName: Build - Windows

      jobs:
      - template: build/ci/build.yml@self
        parameters:
          name: windows
          buildPool:
            name: $(windowsAgentPoolName)
            image: $(windowsImage)
            os: windows
          runAPIScan: true

      - template: sign-artifacts/jobs/v2.yml@internal-templates
        parameters:
          artifactName: output-windows
          usePipelineArtifactTasks: true
          use1ESTemplate: true
          condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
          
    - stage: build_mac
      displayName: Build - Mac
      dependsOn:
      
      jobs:
      - template: build/ci/build.yml@self
        parameters:
          name: macos
          buildPool:
            name: $(macosAgentPoolName)
            vmImage: $(macosImage)
            os: macOS

    - template: build/ci/stage-extended-tests.yml@self
      parameters:
        stageCondition: and(succeeded(), eq('${{ parameters.RunExtendedTests }}', 'true'))
        buildPool:
          name: $(windowsAgentPoolName)
          image: $(windowsImage)
          os: windows
