trigger:
  - main
  - refs/tags/*

pr:
  - main
  
variables:
  AndroidBinderatorVersion: 0.5.2
  AndroidXMigrationVersion: 1.0.8
  DotNetVersion: 6.0.100
  DotNet6Source: https://aka.ms/dotnet6/nuget/index.json
  NuGetOrgSource: https://api.nuget.org/v3/index.json
  LegacyXamarinAndroidPkg: https://public.bl.files.1drv.com/y4meGntxr6evlaRf65G7DtzERXn1TprfopOCzZvbQzQE2CqmV6guKhiYxpaa-AvmMIxRjabZZ0AdfAtbP7-9FwcfDDf-Eztbbz_P5NtSWXmHPZ6v7urX6E9a-Z6ahjczFLqguN4N2RwieC9VKsXZjteDXCzmiXR-TnkvhMS_cGqTLymZEwoqzuEw-kCtrVJ0xixk0qLfFFE_jZm9iy897nQ-Jrfxk2UMd7LBglUBN6nLpU?access_token=EwAAA61DBAAU2kADSankulnKv2PwDjfenppNXFIAAZbzy7pO687YIS3P/1bpY0AWqYKnL8b2YmN235/shAgXi8368HFKSAtRiXgufWoUVAZsdU4e2bBT1pcmCa4NZcCiLrtl6r3p83Broxp0/FUyb3nf/ndohbaRsEzk8CfH5tP9b4F5y3CheFvWabYfXAA/FtTBr3GaNQN5VuU8V%2bmxt7QVLujKCk4vwVRf%2bLGDYMSvI1QjY3oXhiwh3GWtqafb8U6ZHE2sjcA%2bhLv1b49MmU8woAUyZZ%2bOfPDlQcXymu13jEiEqIGHh3oOk%2bXR4g960aFBf8XyrsflwXgX2W6/uopKU02lziuegay/DvBIrBzwts71AdNDrI6Ms2gY/AADZgAACDOuIf6T98Bl0AHUK8YEZzrnAVkuw8WZyu8fKBwiykG/nbaDf7t14n39HOIXaiU4bWy9F%2bKYabbYdiIxULjUmlZtHF99iiM1vfHY1YxL7l9M%2bOOMb/Q5/p0vU1AQSURDiPhpn/BdJY6vQAABXXwKC9dwkvPVo8E4w6jRTRqd4AF27FeSEwCZH86XHizJ6a2dM9Jv79qNh2x2IME9wmcOifIASut1KqnVckyoPbdftltaXZw%2bcNBMoSWQSH8yONMMhRlLH2CKOwK7omVt36IrUC6jqmypkso9d1Z936j6ueXx%2bmeh/gCFMLw6GzwsTgIY3%2b1Doshc0rz4j8Ul3Qd6JRtxuaq2yhR5Bu9LWWXt27GwgZb93Opg0vV1TT3wzVyxXrDwMYzXKHHtMSXoSCN6CWBWSAWiDR7aFUumeP/IDhO9/tZuPoo4K8tXB2uSkZcH/KElKW%2bCPwdisJe/8cNJ1xSKJC%2b8s46z2SPBsW1DQ6delWFO/ZNsF8Ac8%2bNM2pxx66jd5mHwwZPBxKT6jhvau21oZO7Ez/TPKBmD%2bUxARL/EKlSE0SxoBobdn%2bp0nqqIpNYfYDDkrrJc3ItTcz85qGMlIJLj15ZyPBqZx8OcY7MDQQI8mCEw3xu7TQ8C
  LegacyXamarinAndroidVsix: https://aka.ms/xamarin-android-commercial-d17-0-windows
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 120
      validPackagePrefixes: [ 'Xamarin', 'GoogleGson' ]
      areaPath: 'DevDiv\VS Client - Runtime SDKs\Android'
      macosImage: 'macOS-11'                                  # the name of the macOS VM image (BigSur)
      xcode: 13.1
      dotnet: '5.0.403'                                       # the version of .NET Core to use
      dotnetStable: '3.1.415'                                 # the stable version of .NET Core to use
      initSteps:
        - task: UseDotNet@2
          displayName: install .NET $(DotNetVersion)
          inputs:
            version: $(DotNetVersion)
        - pwsh: |
            dotnet workload update --verbosity diag --from-rollback-file workload.json --source $(Dotnet6Source) --source $(NuGetOrgSource)
            dotnet workload install android --verbosity diag --skip-manifest-update --source $(Dotnet6Source) --source $(NuGetOrgSource)
        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '11'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'

      preBuildSteps:
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots $(LegacyXamarinAndroidPkg)
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots $(LegacyXamarinAndroidVsix)
          condition: eq(variables['System.JobName'], 'windows')
      tools:
        - 'xamarin.androidbinderator.tool': '$(AndroidBinderatorVersion)'
        - 'xamarin.androidx.migration.tool': '$(AndroidXMigrationVersion)'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
