trigger:
  - main
  - refs/tags/*

pr:
  - main
  
variables:
  AndroidBinderatorVersion: 0.5.0
  AndroidXMigrationVersion: 1.0.8
  DotNetVersion: 6.0.100-rc.2.21505.57
  DotNet6Source: https://aka.ms/dotnet6/nuget/index.json
  NuGetOrgSource: https://api.nuget.org/v3/index.json
  # NOTE: there wasn't a public release of 16.11 for macOS
  LegacyXamarinAndroidPkg: https://public.bl.files.1drv.com/y4mUmD9K836dCnMFCLH_P0jOV3i4R5dTAI-VIRE3QH8VY8nb0JoWMo_QcLRig-hOs4FQIls3RZqDMT694TdHY2TpNWhptQk6BPKTvKNNAxeRAAmynMsp9WCu-eIt4OwAMKC0g5CD7E--CKSOIP870qO3VwpbW5Y4PjXV4-_z8RRuXeg4UO3CoFfna9CmzhJ_bbOp1p9yzjs7_awjaTi1rT6V1YjqbGfLToaRW7C0BwCLOU?access_token=EwAIA61DBAAU2kADSankulnKv2PwDjfenppNXFIAAS81W2IkgOnMPHT9SPr%2bgLy7MgE1h7HZ8EUUnPcP4/rJMHaT/3ZQRIBo5j1zi0SVdfsBusziQmVtnPdK4xr4xl1Vj9yNxBfNu4a4wmetTOc/5DF/%2bP1jNSnMFZBK1QsjbWePuWCnXFYBBlUquuszqI1nxH93KCTrTICh%2bFkak463oDGock0IjAMFCL3wp1nE3YELQ4agtCIS1Uen3I8A1v2FxzZFhaHnUzXRqw6eVLvbQssFxq%2bRs1dUtoETinfvE%2bmGrt2jVwo03FWsEiCK/U7fF8VnBhoTHljMvr73ARQXalXFHc9jtwH5hxT98F8AWzLbew5Z2RTiRzCCK75xIHQDZgAACIAWQOZX71G82AGAfb2nXzqsj1efxNuILXY1XZvJ7XirHCk/64RiLBPjYvjMwv2u2MmgsntGBwZmuyEtm0cVCHoZNyeDOXs1jWZGymiku8qT5W0eTV/Eu2MrEl00sYPa9pMrlr2HwQYPaRwDOlHwldEUhA41BoPNzWHHqjslNirs3gaW1ZFtCINCseROK2WwMFd3TBNUdbdEyDrP/aq5kg61ex3Kn3N88X1WbURzrKSfe9M8pZW3hbHUyM7m7GNoQgQNVTEIiFeqWNfDEj1PUVRMcq2hYfIfjMhhK1KrtYfKNcCkCUOn7/UDc/2nW2TKMHvOiMpCUwH8wXhoeRlsQ822eIppQynrUdRi/V97gtcliXUKNp8q83kjd5bYSzKoqe8XTFVeKuPR44vMalbzykScGnkzvGZC9Dkz4ZC1a6b8Y4eWOwy/5CnE1NkXKIh8Sb0P8YkQLqb/jO9YW9RNWLSoZtjbtE2T2zNj7ic8z%2bMiiZV85iw6DZMzHxJzQn/lRsaq34A9F7Nn%2bwoFF8eWV8OzpBDaUBgTXWYezFsfjOHST0PexR3nrWLSxBRpWFtD6kcuBuM81%2bFI93mOYPs2YUijxHuAd6I4gVcyDBYtOUwEQPWlt%2bRTG62lZBZEb4O3VnuXDwI%3d
  LegacyXamarinAndroidVsix: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/5375543/main/43243b4d13e8064150770680ec6c34878d6bb047/signed/Xamarin.Android.Sdk-12.1.99.56.vsix
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 120
      validPackagePrefixes: [ 'Xamarin', 'GoogleGson' ]
      areaPath: 'DevDiv\VS Client - Runtime SDKs\Android'
      xcode: 13.0
      initSteps:
        - task: UseDotNet@2
          displayName: install .NET $(DotNetVersion)
          inputs:
            version: $(DotNetVersion)
        - pwsh: |
            dotnet workload update --verbosity diag --from-rollback-file workload.json --source $(Dotnet6Source) --source $(NuGetOrgSource)
            dotnet workload install android --verbosity diag --skip-manifest-update --source $(Dotnet6Source) --source $(NuGetOrgSource)
        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '11'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'

      preBuildSteps:
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots $(LegacyXamarinAndroidPkg)
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots $(LegacyXamarinAndroidVsix)
          condition: eq(variables['System.JobName'], 'windows')
      tools:
        - 'xamarin.androidbinderator.tool': '$(AndroidBinderatorVersion)'
        - 'xamarin.androidx.migration.tool': '$(AndroidXMigrationVersion)'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
