trigger:
  - master
  - refs/tags/*

pr:
  - master
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

  NUGET_BUILD_ID: 4050789

  SIGNING_VM_NAME: VSEng-MicroBuildVS2019
  SIGNING_TYPE: Test
  SIGNING_TEAM_NAME: Test

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
 - job: test_sign
   pool:
     name: $(SIGNING_VM_NAME)
     demands: msbuild
   steps:
     - checkout: none
     - pwsh: echo "Hello World!"
     - task: DownloadBuildArtifacts@0
       inputs:
         buildType: 'specific'
         project: '$(System.TeamProjectId)'
         pipeline: '$(System.DefinitionId)'
         buildVersionToDownload: 'specific'
         buildId: $(NUGET_BUILD_ID)
         downloadType: 'single'
         artifactName: 'nuget'
         downloadPath: 'downloaded'

     - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
        - task: MicroBuildSigningPlugin@2
          inputs:
            signType: $(SIGNING_TYPE)
          env:
            TeamName: $(SIGNING_TEAM_NAME)

        # TODO: SIGN

        - task: MicroBuildCleanup@1
          env:
            TeamName: $(SIGNING_TEAM_NAME)

