trigger:
  - master
  - refs/tags/*

pr:
  - master
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
  DotNetCoreVersion: 3.1.x
  DotNet6Version: 6.0.100-preview.1.21103.13
  DotNet6AndroidMsi:  https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4494116/master/d28ba53e1a6eff1a41e29ec50c60e3d45e6e3168/Microsoft.NET.Workload.Android.11.0.200.117.msi
  DotNet6AndroidPkg:  https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4494116/master/d28ba53e1a6eff1a41e29ec50c60e3d45e6e3168/Microsoft.NET.Workload.Android-11.0.200-ci.d28ba53e1a6eff1a41e29ec50c60e3d45e6e3168.117.pkg
  XamarinAndroidVsix: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/4494116/master/d28ba53e1a6eff1a41e29ec50c60e3d45e6e3168/signed/Xamarin.Android.Sdk-11.2.99.117.vsix
  XamarinAndroidPkg:  https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/4494116/master/d28ba53e1a6eff1a41e29ec50c60e3d45e6e3168/xamarin.android-11.2.99.117.pkg
  # TODO: remove before merging
  NugetSecurityAnalysisWarningLevel: warn
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 120
      validPackagePrefixes: [ 'Xamarin' ]   
      areaPath: 'DevDiv\Xamarin SDK\Android'
      dotnet: ''
      initSteps:
        - task: UseDotNet@2
          displayName: install .NET $(DotNetCoreVersion)
          inputs:
            version: $(DotNetCoreVersion)
            installationPath: /usr/local/share/dotnet/
          condition: eq(variables['System.JobName'], 'macos')
        - bash: >
            export DOTNET_ROOT=/usr/local/share/dotnet/ &&
            export PATH="$DOTNET_ROOT:~/.dotnet/tools:$PATH" &&
            curl -L https://dot.net/v1/dotnet-install.sh > dotnet-install.sh &&
            sh dotnet-install.sh --version $(DotNet6Version) --install-dir $DOTNET_ROOT --verbose &&
            dotnet --list-sdks &&
            echo "##vso[task.setvariable variable=PATH]$PATH"
          displayName: install .NET $(DotNet6Version)
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            $ProgressPreference = 'SilentlyContinue'
            Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
            & .\dotnet-install.ps1 -Version $(DotNet6Version) -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
            & dotnet --list-sdks
          displayName: install .NET $(DotNet6Version)
          condition: eq(variables['System.JobName'], 'windows')
      preBuildSteps:
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
          displayName: install .NET global tools
        - pwsh: |
            boots $(DotNet6AndroidPkg)
            boots $(XamarinAndroidPkg)
          condition: eq(variables['System.JobName'], 'macos')
          displayName: install Xamarin.Android
        - pwsh: |
            boots $(DotNet6AndroidMsi)
            boots $(XamarinAndroidVsix)
          condition: eq(variables['System.JobName'], 'windows')
          displayName: install Xamarin.Android
      tools:
        - 'xamarin.androidbinderator.tool': '0.4.2'
        - 'xamarin.androidx.migration.tool': '1.0.7.1'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
