trigger:
  - main
  - refs/tags/*

pr:
  - main
  
variables:
  AndroidBinderatorVersion: 0.4.9
  AndroidXMigrationVersion: 1.0.8
  DotNetVersion: 6.0.100-preview.7.21379.14
  LegacyXamarinAndroidPkg: https://aka.ms/xamarin-android-commercial-d16-10-macos
  LegacyXamarinAndroidVsix: https://aka.ms/xamarin-android-commercial-d16-10-windows
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 120
      validPackagePrefixes: [ 'Xamarin' ]   
      areaPath: 'DevDiv\Xamarin SDK\Android'
      initSteps:
        - task: UseDotNet@2
          displayName: install .NET $(DotNetVersion)
          inputs:
            version: $(DotNetVersion)
        - pwsh: |
            dotnet workload install android
      preBuildSteps:
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots $(LegacyXamarinAndroidPkg)
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots $(LegacyXamarinAndroidVsix)
          condition: eq(variables['System.JobName'], 'windows')
      tools:
        - 'xamarin.androidbinderator.tool': '$(AndroidBinderatorVersion)'
        - 'xamarin.androidx.migration.tool': '$(AndroidXMigrationVersion)'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
