trigger:
  - main
  - refs/tags/*

pr:
  - main
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 120
      validPackagePrefixes: [ 'Xamarin' ]   
      areaPath: 'DevDiv\Xamarin SDK\Android'
      preBuildSteps:
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots https://public.bl.files.1drv.com/y4mOAZRA34VYFZP0MjgadUFmtH-OrFAqdEgZf8gbT8eQaa0LuTZxXPguTN5NS91RHlk84I6h83sPL8ewZ6v2lIfn5Na16KRtGuhEMSVFuPaGRZttyV6izXoX1RP7oQdI3wYaFUyzvcwUiFZvPDIZbpOYQgC_jAYeyu0phpyme2mEZvdHMRbROm37NGrTYbnzlC3Va1LeOig2nPiP9y3qq9zEgp0HyYwOjNaiaFwz_9zPVw?access_token=EwAQA61DBAAUmcDj0azQ5tf1lkBfAvHLBzXl5ugAAVK8DLb82L0tL9oUlzVXa0u5O6E/7d4l4eca6%2bPFjjd5MG5Y6LA1qr8V4D%2bAg9OFHbIWYIaF2Zz%2bPEShwtMHeo6yBufXk5ioHq76hrLU1Zhlzbdtt5vQAhf7nH4RrZ9e9BJHPrJRbwtJIlzTi2/F0CKQxW1Isj6hoiHTeecoT11ze8UjwMGEzikvtT57/edJmCFTZS%2bb4E%2bZrajie7IZmWGNXpL41sKXOJ92UeXcCzlnVT/imkh1PL7FzsLi2rL2oIm810bqkHKV67GcshCfurqEIBfPRaQ3jITSNcHJiaPhJQGfekE2U4mdynwprJhP0DtiTi/RCbTKIp1Pat/RVNYDZgAACNzgX0PiV4Rb4AGXKPsejs08Ddp8SdqF12cZXwqoz8OD36GN2vvNrN409REFm/5rSBAgWvvJHCULWmNmj1FKldDK0FG4YE%2bxf0qZlQlANPtmfTMebaeQlQAAE/SByQd3ftHA256Vy8/Jj1KsO%2bw/Ctabjji4mtgP6HNaYvXkqap17ZeLHT4AtVoGQxJu9dDs7XPyKKN1b7OgLMMWC9uy6/S909pE%2bxMuMvKDS8lkdAykgrnPh6o3U5QW2wbm/fGM9P49vUrBKz1ZlKyQQled4/cNm2QMmfGEGAj6VpjdTZebikTQsAlIpAW3S6E%2bmRGe/WZMRecMZ7uVNCQG9M0YsFsdroUqaq9murvN/fdNwLh3cELmdTLAS6KUZRutKUd4WBF3oB9Bf0oLfDtx0ApjSitGiPNa1rBX/cNWiXVYwGgGYqOweluz7Xv8Iiytb68MBy5Z9a8D3A02Lu%2bjOffbMIuG57FXN9KKyFf5Q06qYJjBmRSCfyMGGiWfuyLtcWyPypoGB7clwVdMnCxniplJybQYewXQ47XHtSUamdEEZZleqswqm5AMFodJ58d3y3tHkj1rq5%2bHrgUwaYGjpozHOjQLoOasq4%2b6KGbpeWL1OBtPh8UffVg6ydSQ/1V5K4oLvyvhIYoa1iCu8KcNAg%3d%3d
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots https://public.bl.files.1drv.com/y4m4amAM9jtJstpNH3yCE2uxNgmb3dfSnNwfxBlw6kuEwao8UJGJoAhUn7O_KqtajQwXoKVtl5GNk9AC-1OV-EJTcLziDKM3cVKJdWKvt1atVnuKrL64rBBRFJ6SSXudavx8dVfO93DbFUubWdawL0-qfhrM7DbUYcYfamM6X6zBcmFSQpPtLgcIulHxzz5JPuoQygWHYKOssCLgzAGpU7a-0dgzSN815uA4sZmstRHXZI?access_token=EwAQA61DBAAUmcDj0azQ5tf1lkBfAvHLBzXl5ugAAVK8DLb82L0tL9oUlzVXa0u5O6E/7d4l4eca6%2bPFjjd5MG5Y6LA1qr8V4D%2bAg9OFHbIWYIaF2Zz%2bPEShwtMHeo6yBufXk5ioHq76hrLU1Zhlzbdtt5vQAhf7nH4RrZ9e9BJHPrJRbwtJIlzTi2/F0CKQxW1Isj6hoiHTeecoT11ze8UjwMGEzikvtT57/edJmCFTZS%2bb4E%2bZrajie7IZmWGNXpL41sKXOJ92UeXcCzlnVT/imkh1PL7FzsLi2rL2oIm810bqkHKV67GcshCfurqEIBfPRaQ3jITSNcHJiaPhJQGfekE2U4mdynwprJhP0DtiTi/RCbTKIp1Pat/RVNYDZgAACNzgX0PiV4Rb4AGXKPsejs08Ddp8SdqF12cZXwqoz8OD36GN2vvNrN409REFm/5rSBAgWvvJHCULWmNmj1FKldDK0FG4YE%2bxf0qZlQlANPtmfTMebaeQlQAAE/SByQd3ftHA256Vy8/Jj1KsO%2bw/Ctabjji4mtgP6HNaYvXkqap17ZeLHT4AtVoGQxJu9dDs7XPyKKN1b7OgLMMWC9uy6/S909pE%2bxMuMvKDS8lkdAykgrnPh6o3U5QW2wbm/fGM9P49vUrBKz1ZlKyQQled4/cNm2QMmfGEGAj6VpjdTZebikTQsAlIpAW3S6E%2bmRGe/WZMRecMZ7uVNCQG9M0YsFsdroUqaq9murvN/fdNwLh3cELmdTLAS6KUZRutKUd4WBF3oB9Bf0oLfDtx0ApjSitGiPNa1rBX/cNWiXVYwGgGYqOweluz7Xv8Iiytb68MBy5Z9a8D3A02Lu%2bjOffbMIuG57FXN9KKyFf5Q06qYJjBmRSCfyMGGiWfuyLtcWyPypoGB7clwVdMnCxniplJybQYewXQ47XHtSUamdEEZZleqswqm5AMFodJ58d3y3tHkj1rq5%2bHrgUwaYGjpozHOjQLoOasq4%2b6KGbpeWL1OBtPh8UffVg6ydSQ/1V5K4oLvyvhIYoa1iCu8KcNAg%3d%3d
          condition: eq(variables['System.JobName'], 'windows')
      tools:
        - 'xamarin.androidbinderator.tool': '0.4.2'
        - 'xamarin.androidx.migration.tool': '1.0.7.1'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
