trigger:
  - main
  - refs/tags/*

pr:
  - main
  
variables:
  AndroidBinderatorVersion: 0.5.4
  AndroidXMigrationVersion: 1.0.10
  BootsVersion: 1.1.0.712-preview2
  DotNetVersion: 6.0.403
  XcodeVersion: 13.3.1
  DotNet6Source: https://aka.ms/dotnet6/nuget/index.json
  NuGetOrgSource: https://api.nuget.org/v3/index.json
  XamarinDotNetWorkloadSource: workloads.json   # or url (check for recent versions - redth)
                                                # https://aka.ms/dotnet/maui/6.0.401.json
  # matching builds
  LegacyXamarinAndroidPkg:  https://aka.ms/xamarin-android-commercial-d17-3-macos
  LegacyXamarinAndroidVsix: https://aka.ms/xamarin-android-commercial-d17-3-windows
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main

jobs:
  - template: build/ci/build.yml
    parameters:
      timeoutInMinutes: 150
      validPackagePrefixes: [ 'Xamarin', 'GoogleGson' ]
      areaPath: 'DevDiv\VS Client - Runtime SDKs\Android'
      macosImage: internal-macos12                            # macOS VM image name, must be "internal" locked down image
      windowsAgentPoolName: android-win-2022
      xcode: $(XcodeVersion)
      dotnet: $(DotNetVersion)                                # the version of .NET Core to use
      dotnetStable: $(DotNetVersion)                          # the stable version of .NET Core to use
      dotnetWorkloadRollbackFile: $(XamarinDotNetWorkloadSource)
      dotnetWorkloadSource: $(DotNet6Source)
      dotnetNuGetOrgSource: $(NuGetOrgSource)

      tools:
        - 'xamarin.androidbinderator.tool': '$(AndroidBinderatorVersion)'
        - 'Cake.Tool': '2.2.0'
        - 'boots': '$(BootsVersion)'
        - 'api-tools': '1.3.4'
        
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

    - template: compliance/sbom/job.v1.yml@internal-templates
      parameters:
        dependsOn: signing
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        artifactNames: [ nuget-signed ]
        packageName: androidx
        packageFilter: '*.nupkg'
