trigger:
  - master
  - refs/tags/*

pr:
  - master
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

  NUGET_BUILD_ID: 4050789

  SIGNING_VM_NAME: VSEng-MicroBuildVS2019
  SIGNING_TYPE: Test
  SIGNING_TEAM_NAME: Xamarin
  SIGNING_ARTIFACT_NAME: nuget

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
 - job: test_sign
   pool:
     name: $(SIGNING_VM_NAME)
     demands: 
       - msbuild
   steps:
     - checkout: none
     - powershell: echo "Hello World!"
     - task: DownloadBuildArtifacts@0
       inputs:
         buildType: 'specific'
         project: '$(System.TeamProjectId)'
         pipeline: '$(System.DefinitionId)'
         buildVersionToDownload: 'specific'
         buildId: $(NUGET_BUILD_ID)
         downloadType: 'single'
         artifactName: '$(SIGNING_ARTIFACT_NAME)'
         downloadPath: 'unsigned'

     - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
        - task: MicroBuildSigningPlugin@2
          inputs:
            signType: '$(SIGNING_TYPE)'
          env:
            TeamName: '$(SIGNING_TEAM_NAME)'

        - powershell: |
            $downloader = New-Object System.Net.WebClient
            $downloader.Headers["Authorization"] = 'token $(Github.Token)'
            $downloader.DownloadFile(
              "https://raw.githubusercontent.com/xamarin/yaml-templates/mattleibow/v2-sign-artifacts/sign-artifacts/steps/v2-SignFiles.proj",
              "SignFiles.proj")
            $downloader.DownloadFile(
              "https://raw.githubusercontent.com/xamarin/yaml-templates/mattleibow/v2-sign-artifacts/sign-artifacts/steps/v2-ExtractNupkgs.ps1",
              "ExtractNupkgs.ps1")

        - powershell: .\ExtractNupkgs.ps1 -UnsignedDir "unsigned" -WorkingDir "working\extracted"

        - task: MSBuild@1
          inputs:
            solution: SignFiles.proj
            msbuildArguments: /t:SignFiles /p:SignType="$(SIGNING_TYPE)" /p:WorkingDir="working\extracted" /bl:binlogs\sign-contents.binlog'

        - task: NuGetCommand@2
          inputs:
            command: 'pack'
            packagesToPack: 'working\extracted\*\*.nuspec'
            packDestination: 'working\packed'

        - task: MSBuild@1
          inputs:
            solution: SignFiles.proj
            msbuildArguments: /t:SignFiles /p:SignType="$(SIGNING_TYPE)" /p:WorkingDir="working\packed" /bl:binlogs\sign-packages.binlog'

        - task: CopyFiles@2
          inputs:
            sourceFolder: 'working\packed'
            targetFolder: 'signed'

        - task: MicroBuildCleanup@1
          env:
            TeamName: '$(SIGNING_TEAM_NAME)'
