trigger:
  - master
  - refs/tags/*

pr:
  - master
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

  SIGNING_VM_NAME: VSEng-MicroBuildVS2019
  SIGNING_TYPE: Test

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
 - job: test_sign
   pool:
     name: $(SIGNING_VM_NAME)
     demands: msbuild
   steps:
     - checkout: none
     - pwsh: echo "Hello World!"
     
     - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
        - pwsh: echo "Hello DevDiv!"
      
#         - task: MicroBuildSigningPlugin@2
#           inputs:
#             signType: $(SIGNING_TYPE)
#     - job
#       - task: DownloadBuildArtifacts@0
#         displayName: Download the pre-built ${{ parameters.name }} artifacts
#         inputs:
#           buildType: 'specific'
#           project: '$(System.TeamProjectId)'
#           pipeline: '$(System.DefinitionId)'
#           buildVersionToDownload: 'specific'
#           buildId: '${{ parameters.buildExternals }}'
#           downloadType: 'single'
#           artifactName: ${{ parameters.name }}
#           downloadPath: 'download-temp'
