trigger:
  - main
  - refs/tags/*

pr:
  - main
  
variables:
  AndroidBinderatorVersion: 0.5.4
  AndroidXMigrationVersion: 1.0.9
  BootsVersion: 1.1.0.712-preview2
  DotNetVersion: 6.0.300
  DotNet6Source: https://aka.ms/dotnet6/nuget/index.json
  NuGetOrgSource: https://api.nuget.org/v3/index.json
  XamarinDotNetWorkloadSource: https://aka.ms/dotnet/maui/rc.3.json
  LegacyXamarinAndroidPkg: https://aka.ms/xamarin-android-commercial-d17-0-macos
  LegacyXamarinAndroidVsix: https://aka.ms/xamarin-android-commercial-d17-2-windows
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 120
      validPackagePrefixes: [ 'Xamarin', 'GoogleGson' ]
      areaPath: 'DevDiv\VS Client - Runtime SDKs\Android'
      macosImage:                                             # the name of the macOS VM image (BigSur) - Disabled until we have newer XA classic packages
      windowsAgentPoolName: android-win-2022
      xcode: 13.3.1
      dotnet: '6.0.300'                                       # the version of .NET Core to use
      dotnetStable: '6.0.300'                                 # the stable version of .NET Core to use
      initSteps:
        - task: UseDotNet@2
          displayName: install .NET $(DotNetVersion)
          inputs:
            version: $(DotNetVersion)
        - pwsh: |
            dotnet workload update --verbosity diag --from-rollback-file $(XamarinDotNetWorkloadSource) --source $(Dotnet6Source) --source $(NuGetOrgSource)
            dotnet workload install android --verbosity diag --skip-manifest-update --source $(Dotnet6Source) --source $(NuGetOrgSource)
        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '11'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'

      preBuildSteps:
        - pwsh: |
            dotnet tool update --global Cake.Tool
            dotnet tool update --global boots --version $(BootsVersion)
            boots $(LegacyXamarinAndroidPkg)
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            dotnet tool update --global Cake.Tool
            dotnet tool update --global boots --version $(BootsVersion)
            boots --url $(LegacyXamarinAndroidVsix) --downgrade-first
          condition: eq(variables['System.JobName'], 'windows')
          
      postDiffBuildSteps:
        - pwsh: |
            dotnet cake utilities.cake -t=verify-namespace-file
          displayName: Verify published namespaces
      tools:
        - 'xamarin.androidbinderator.tool': '$(AndroidBinderatorVersion)'
        - 'xamarin.androidx.migration.tool': '$(AndroidXMigrationVersion)'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

    - template: compliance/sbom/job.v1.yml@internal-templates
      parameters:
        dependsOn: signing
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        artifactNames: [ nuget-signed ]
        packageName: androidx
        packageFilter: '*.nupkg'
