trigger:
  - main
  - refs/tags/*

pr:
  - main
  
parameters:
- name: RunExtendedTests
  default: true
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)

  # Build variables
  mainBranchName: main                                                                  # Name of Git "main" branch
  configuration: Release                                                                # Build configuration: 'Debug', 'Release'

  # Reporting variables
  areaPath: DevDiv\VS Client - Runtime SDKs\Android                                     # AzDo area path to log any issues

  # Windows specific variables
  windowsAgentPoolName: Maui-1ESPT                                                      # Windows VM pool name
  windowsImage: 1ESPT-Windows2022                                                       # Windows VM image name
  
  # macOS specific variables
  macosAgentPoolName: Azure Pipelines                                                   # macOS VM pool name
  macosImage: internal-macos12                                                          # macOS VM image name

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:   
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
      
    stages:
    - stage: build_windows
      displayName: Build - Windows

      jobs:
      - template: build/ci/build.yml@self
        parameters:
          name: windows
          buildPool:
            name: $(windowsAgentPoolName)
            image: $(windowsImage)
            os: windows
          mainBranchName: $(mainBranchName)
          configuration: $(configuration)
          runAPIScan: true

      - template: sign-artifacts/jobs/v2.yml@internal-templates
        parameters:
          artifactName: output-windows
          usePipelineArtifactTasks: true
          use1ESTemplate: true
          condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
          
    - stage: build_mac
      displayName: Build - Mac
      dependsOn:
      
      jobs:
      - template: build/ci/build.yml@self
        parameters:
          name: macos
          buildPool:
            name: $(macosAgentPoolName)
            vmImage: $(macosImage)
            os: macOS
          mainBranchName: $(mainBranchName)
          configuration: $(configuration)

    - template: build/ci/stage-extended-tests.yml@self
      parameters:
        stageCondition: and(succeeded(), eq('${{ parameters.RunExtendedTests }}', 'true'))
        configuration: $(configuration)
        buildPool:
          name: $(windowsAgentPoolName)
          image: $(windowsImage)
          os: windows
