name: Log Disk Space
description: Logs disk space usage on the runner
inputs:
  detailed:
    description: 'Whether to include detailed disk analysis (true/false)'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
  - name: Log disk space
    shell: bash
    run: |
      echo "=== Disk Space Usage ==="
      df -h
      echo ""
      echo "=== Disk Usage by Directory (/) ==="
      du -h -d 1 / 2>/dev/null | sort -hr | head -20 || true
      echo ""
      echo "=== Disk Usage in Current Directory ==="
      du -h -d 1 . 2>/dev/null | sort -hr | head -20 || true
      echo ""
      echo "=== Disk Usage Summary ==="
      df -h / | tail -1 | awk '{print "Used: " $3 " / " $2 " (" $5 " full)"}'
      
      # Detailed analysis if requested
      if [ "${{ inputs.detailed }}" = "true" ]; then
        echo ""
        echo "=== DETAILED ANALYSIS ==="
        echo ""
        echo "=== Largest directories in /home/runner ==="
        sudo du -h /home/runner 2>/dev/null | sort -rh | head -20
        echo ""
        echo "=== Largest directories in /opt ==="
        sudo du -h /opt 2>/dev/null | sort -rh | head -20
        echo ""
        echo "=== Workspace breakdown (top level) ==="
        du -h --max-depth=1 . 2>/dev/null | sort -rh
        echo ""
        echo "=== Workspace breakdown (2 levels deep) ==="
        du -h --max-depth=2 . 2>/dev/null | sort -rh | head -30
        echo ""
        echo "=== externals directory ==="
        du -sh ./externals/* 2>/dev/null | sort -rh | head -20 || echo "No externals"
        echo ""
        echo "=== output directory ==="
        du -sh ./output/* 2>/dev/null | sort -rh | head -20 || echo "No output"
        echo ""
        echo "=== generated directory ==="
        du -sh ./generated/* 2>/dev/null | sort -rh | head -20 || echo "No generated"
        echo ""
        echo "=== /mnt disk usage ==="
        du -h --max-depth=1 /mnt 2>/dev/null | sort -rh
        echo ""
        echo "=== Docker usage ==="
        docker system df 2>/dev/null || echo "Docker not available"
        echo ""
        echo "=== Temp directories ==="
        du -sh /tmp /var/tmp 2>/dev/null || true
      fi
