name: "Weekly Stable Updates"

on:
  #schedule:
    # Run every Monday at 9:00 AM UTC
  #  - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  create-weekly-issue:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    
    - name: Create weekly stable updates issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const date = '${{ steps.date.outputs.date }}';
          const title = `Stable Updates ${date}`;
          const body = `Run the following commands:
          \`\`\`
          dotnet cake -t:update-config
          dotnet cake utilities.cake -t=generate-component-governance
          dotnet cake utilities.cake -t=generate-namespace-file
          dotnet cake utilities.cake -t=list-artifacts
          \`\`\`

          Commit the changes.

          Lastly, run:
          \`\`\`
          dotnet cake utilities.cake -t=api-diff-markdown-info-pr
          \`\`\`

          And put the contents from this command in the PR description and commit messages.`;

          const response = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            assignees: ['copilot-swe-agent']
          });
          
          console.log(`Created issue #${response.data.number}: ${response.data.title}`);
